### ISSUE TITLE
Initial teamcenter setup

### ISSUE THREAD

**Issue by nwies** [Krusty84/Teamcenter_ZABBIX_Templates#1]
Hello,

Thanks for your work identifying the queries to monitor a teamcenter.

I would like to reproduce it on a prometheus + jmx exporter. 

Could you please help me to set it up? 
What services did you enable on teamcenter side? 

Could you give me back some of the jmx queries to type on the jconsole in order for me to understand what to write on the jmx exporter config.

By the end, I will share with you my results and also with the jmx exporter team.

BR
WIES Nicolas

**Comment by Krusty84** [comment]
Hi,
Do you have access to Teamcenter Documentation?

**Comment by nwies** [comment]
Yes, of course, my teamcenteris under maintenance

**Comment by Krusty84** [comment]
Okay, more details you can get from TC Docs (you should use **jmx** as keyword)
as example
https://docs.sw.siemens.com/en-US/product/282219420/doc/PL20200109161503476.plm00102/html/id1680392?audience=external


Anyway...

**For FSC:**

**bin\TcFSCService.exe -install** "%SERVICE_NAME%" %FSC_JVM% -Xms%FSC_MEM% -Xmx%FSC_MEM% -Dcom.sun.management.jmxremote **-Dcom.sun.management.jmxremote.port=9010** 
-Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false 

-Dcom.sun.management.jmxremote.ssl=false -Djava.class.path=%FSC_CP% -Djava.library.path=%FMS_HOME%/lib -Dfms.home=%FMS_HOME% -Dfms.config=fmsmaster_%FSCID%.xml -Dfsc.config=%FSCID%.xml -Dsun.net.client.defaultConnectTimeout=90000 -Dsun.net.client.defaultReadTimeout=90000 -Dcom.teamcenter.mld.logging.prefix=%FSCID% -start com.teamcenter.fms.servercache.FMSServerCache -stop com.teamcenter.fms.servercache.FMSServerCache -method stop -out %FSCID%stdout.log -err %FSCID%stderr.log -current %FMS_HOME% -path lib;%JAVA_HOME%\bin

**For Pool Manager:**
in mgrenv.bat or in Installmgr.bat (for installing Pool Manager as daemon):

set JVM_OPTS=%SERVER% %JAVA_MEM_ARGS% %JacORB_ARGS% -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote **-Dcom.sun.management.jmxremote.port=9040** -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.teamcenter.jeti.util.log.category=ServerManager -Djava.class.path="%CLASSPATH%" -Djava.library.path="%REL_LOC%"


**For Web-Tier:**
Open the **webtierMonitorConfig.xml** from ....tc.ear\lib\**mldcfg.jar** in the <ApplicationConfig set mode as Normal
Save this file and redeploy tc.war after first login in the TC you can get various metrics about WebTier and partial about Pool Manager

for Web Logic

**setDomainEnv.cmd**


set SERVER_CLASS=weblogic.Server

set JAVA_PROPERTIES=%JAVA_PROPERTIES% %WLP_JAVA_PROPERTIES%

**set JAVA_OPTIONS**=%JAVA_OPTIONS% -Dcom.sun.management.jmxremote **-Dcom.sun.management.jmxremote.port=9020** -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false %JAVA_PROPERTIES%


I hope that it will be helping you

**Comment by nwies** [comment]
Hello,

I just update my Teamcenter in order to enable the jmx .
I look on the Windows registry in order to had the missing jvm parameters.
all Teamcenter services are under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\

the trick is to add a new jvm parameters for each, to renumber the existing ones and change the "Options Count"
For the picture below teh registry before, on the right the registry after.

![image](https://user-images.githubusercontent.com/10389749/133748612-07396519-ae89-4dc0-b2ca-77092fa3d115.png)


Thanks a lot for your help.
we can close this issue.

**Comment by nwies** [comment]
hello,

As follow up , please find : 
The Prometheus Jmx export http server config files I set for all the 4 part (FSCPOOL/SOLR/TOMCAT) and their cmd file (I define Windows services with nssm for it)
The Grafana dashboard 
Some pictures of the Dashboard

Hope it will help other
BR
[tomcat_full.yml.txt](https://github.com/Krusty84/Teamcenter_ZABBIX_Templates/files/7233283/tomcat_full.yml.txt)
[fsc_full.yml.txt](https://github.com/Krusty84/Teamcenter_ZABBIX_Templates/files/7233284/fsc_full.yml.txt)
[jmx_http_exporter_fsc.cmd.txt](https://github.com/Krusty84/Teamcenter_ZABBIX_Templates/files/7233285/jmx_http_exporter_fsc.cmd.txt)
[jmx_http_exporter_pool.cmd.txt](https://github.com/Krusty84/Teamcenter_ZABBIX_Templates/files/7233286/jmx_http_exporter_pool.cmd.txt)
[jmx_http_exporter_solr.cmd.txt](https://github.com/Krusty84/Teamcenter_ZABBIX_Templates/files/7233287/jmx_http_exporter_solr.cmd.txt)
[jmx_http_exporter_tomcat.cmd.txt](https://github.com/Krusty84/Teamcenter_ZABBIX_Templates/files/7233288/jmx_http_exporter_tomcat.cmd.txt)
[pool_full.yml.txt](https://github.com/Krusty84/Teamcenter_ZABBIX_Templates/files/7233289/pool_full.yml.txt)
[prometheus_teamcenter_monitoring.pdf](https://github.com/Krusty84/Teamcenter_ZABBIX_Templates/files/7233290/prometheus_teamcenter_monitoring.pdf)
[grafana_dashboard_teamcenter_monitoring.json.txt](https://github.com/Krusty84/Teamcenter_ZABBIX_Templates/files/7233291/grafana_dashboard_teamcenter_monitoring.json.txt)
[solr_full.yml.txt](https://github.com/Krusty84/Teamcenter_ZABBIX_Templates/files/7233292/solr_full.yml.txt)
